// Generated by dbus-codegen. Do not edit.
import DBUS

private enum DBusCodegenError: Error { case typeMismatch }

// MARK: - org.freedesktop.DBus

public protocol OrgFreedesktopDBus: Sendable {
	func hello() async throws -> String
	func requestName(arg: String, arg: UInt32) async throws -> UInt32
	func releaseName(arg: String) async throws -> UInt32
	func startServiceByName(arg: String, arg: UInt32) async throws -> UInt32
	func updateActivationEnvironment(arg: [String: String]) async throws
	func nameHasOwner(arg: String) async throws -> Bool
	func listNames() async throws -> [String]
	func listActivatableNames() async throws -> [String]
	func addMatch(arg: String) async throws
	func removeMatch(arg: String) async throws
	func getNameOwner(arg: String) async throws -> String
	func listQueuedOwners(arg: String) async throws -> [String]
	func getConnectionUnixUser(arg: String) async throws -> UInt32
	func getConnectionUnixProcessID(arg: String) async throws -> UInt32
	func getAdtAuditSessionData(arg: String) async throws -> [UInt8]
	func getConnectionSELinuxSecurityContext(arg: String) async throws -> [UInt8]
	func getConnectionAppArmorSecurityContext(arg: String) async throws -> String
	func reloadConfig() async throws
	func getId() async throws -> String
	func getConnectionCredentials(arg: String) async throws -> [String: DBusVariant]
	var features: [String] { get async throws }
	var interfaces: [String] { get async throws }
	func nameOwnerChanged() async throws -> AsyncStream<(arg: String, arg: String, arg: String)>
	func nameLost() async throws -> AsyncStream<String>
	func nameAcquired() async throws -> AsyncStream<String>
	func activatableServicesChanged() async throws -> AsyncStream<Void>
}

public struct OrgFreedesktopDBusProxy: OrgFreedesktopDBus {
	private let connection: DBusClient.Connection
	private let destination: String
	private let path: String

	public init(connection: DBusClient.Connection, destination: String, path: String) {
		self.connection = connection
		self.destination = destination
		self.path = path
	}

	public func hello() async throws -> String {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "Hello",
			body: [],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .string(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func requestName(arg: String, arg: UInt32) async throws -> UInt32 {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "RequestName",
			body: [.string(arg), .uint32(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .uint32(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func releaseName(arg: String) async throws -> UInt32 {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "ReleaseName",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .uint32(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func startServiceByName(arg: String, arg: UInt32) async throws -> UInt32 {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "StartServiceByName",
			body: [.string(arg), .uint32(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .uint32(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func updateActivationEnvironment(arg: [String: String]) async throws {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "UpdateActivationEnvironment",
			body: [
				.dictionary(
					Dictionary(uniqueKeysWithValues: arg.map { (.string($0.key), .string($0.value)) })
				)
			],
		)
		_ = try await connection.send(request)
	}

	public func nameHasOwner(arg: String) async throws -> Bool {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "NameHasOwner",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .boolean(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func listNames() async throws -> [String] {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "ListNames",
			body: [],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .array(let _arr0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return try _arr0.map { elem in
			guard case .string(let s) = elem else { throw DBusCodegenError.typeMismatch }
			return s
		}
	}

	public func listActivatableNames() async throws -> [String] {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "ListActivatableNames",
			body: [],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .array(let _arr0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return try _arr0.map { elem in
			guard case .string(let s) = elem else { throw DBusCodegenError.typeMismatch }
			return s
		}
	}

	public func addMatch(arg: String) async throws {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "AddMatch",
			body: [.string(arg)],
		)
		_ = try await connection.send(request)
	}

	public func removeMatch(arg: String) async throws {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "RemoveMatch",
			body: [.string(arg)],
		)
		_ = try await connection.send(request)
	}

	public func getNameOwner(arg: String) async throws -> String {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "GetNameOwner",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .string(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func listQueuedOwners(arg: String) async throws -> [String] {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "ListQueuedOwners",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .array(let _arr0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return try _arr0.map { elem in
			guard case .string(let s) = elem else { throw DBusCodegenError.typeMismatch }
			return s
		}
	}

	public func getConnectionUnixUser(arg: String) async throws -> UInt32 {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "GetConnectionUnixUser",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .uint32(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func getConnectionUnixProcessID(arg: String) async throws -> UInt32 {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "GetConnectionUnixProcessID",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .uint32(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func getAdtAuditSessionData(arg: String) async throws -> [UInt8] {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "GetAdtAuditSessionData",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .array(let _arr0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return try _arr0.map { elem in
			guard case .byte(let b) = elem else { throw DBusCodegenError.typeMismatch }
			return b
		}
	}

	public func getConnectionSELinuxSecurityContext(arg: String) async throws -> [UInt8] {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "GetConnectionSELinuxSecurityContext",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .array(let _arr0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return try _arr0.map { elem in
			guard case .byte(let b) = elem else { throw DBusCodegenError.typeMismatch }
			return b
		}
	}

	public func getConnectionAppArmorSecurityContext(arg: String) async throws -> String {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "GetConnectionAppArmorSecurityContext",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .string(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func reloadConfig() async throws {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "ReloadConfig",
			body: [],
		)
		_ = try await connection.send(request)
	}

	public func getId() async throws -> String {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "GetId",
			body: [],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .string(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func getConnectionCredentials(arg: String) async throws -> [String: DBusVariant] {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus",
			method: "GetConnectionCredentials",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .dictionary(let _dict0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return try Dictionary(
			uniqueKeysWithValues: _dict0.map { k, v in
				guard case .string(let key) = k, case .variant(let val) = v else {
					throw DBusCodegenError.typeMismatch
				}
				return (key, val)
			}
		)
	}

	public var features: [String] {
		get async throws {
			let request = DBusRequest.createMethodCall(
				destination: destination,
				path: path,
				interface: "org.freedesktop.DBus.Properties",
				method: "Get",
				body: [.string("org.freedesktop.DBus"), .string("Features")],
			)
			guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
			guard case .variant(let _variant0) = reply.body[0] else {
				throw DBusCodegenError.typeMismatch
			}
			guard case .array(let _arr0) = _variant0.value else { throw DBusCodegenError.typeMismatch }
			return try _arr0.map { elem in
				guard case .string(let s) = elem else { throw DBusCodegenError.typeMismatch }
				return s
			}
		}
	}

	public var interfaces: [String] {
		get async throws {
			let request = DBusRequest.createMethodCall(
				destination: destination,
				path: path,
				interface: "org.freedesktop.DBus.Properties",
				method: "Get",
				body: [.string("org.freedesktop.DBus"), .string("Interfaces")],
			)
			guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
			guard case .variant(let _variant0) = reply.body[0] else {
				throw DBusCodegenError.typeMismatch
			}
			guard case .array(let _arr0) = _variant0.value else { throw DBusCodegenError.typeMismatch }
			return try _arr0.map { elem in
				guard case .string(let s) = elem else { throw DBusCodegenError.typeMismatch }
				return s
			}
		}
	}

	public func nameOwnerChanged() async throws -> AsyncStream<
		(arg: String, arg: String, arg: String)
	> {
		_ = try await connection.send(
			DBusRequest.createMethodCall(
				destination: "org.freedesktop.DBus",
				path: "/org/freedesktop/DBus",
				interface: "org.freedesktop.DBus",
				method: "AddMatch",
				body: [.string("type='signal',interface='org.freedesktop.DBus',member='NameOwnerChanged'")],
			)
		)
		let rawStream = await connection.subscribeToSignal(
			interface: "org.freedesktop.DBus",
			member: "NameOwnerChanged",
		)
		return AsyncStream<(arg: String, arg: String, arg: String)> { continuation in
			let task = Task {
				for await message in rawStream {
					guard message.body.count >= 3 else { continue }
					guard
						let _sig0 = { () -> String? in
							if case .string(let v) = message.body[0] { return v }
							return nil
						}()
					else { continue }
					guard
						let _sig1 = { () -> String? in
							if case .string(let v) = message.body[1] { return v }
							return nil
						}()
					else { continue }
					guard
						let _sig2 = { () -> String? in
							if case .string(let v) = message.body[2] { return v }
							return nil
						}()
					else { continue }
					continuation.yield((arg: _sig0, arg: _sig1, arg: _sig2))
				}
				continuation.finish()
			}
			continuation.onTermination = { _ in task.cancel() }
		}
	}

	public func nameLost() async throws -> AsyncStream<String> {
		_ = try await connection.send(
			DBusRequest.createMethodCall(
				destination: "org.freedesktop.DBus",
				path: "/org/freedesktop/DBus",
				interface: "org.freedesktop.DBus",
				method: "AddMatch",
				body: [.string("type='signal',interface='org.freedesktop.DBus',member='NameLost'")],
			)
		)
		let rawStream = await connection.subscribeToSignal(
			interface: "org.freedesktop.DBus",
			member: "NameLost",
		)
		return AsyncStream<String> { continuation in
			let task = Task {
				for await message in rawStream {
					guard message.body.count >= 1 else { continue }
					guard
						let _sig0 = { () -> String? in
							if case .string(let v) = message.body[0] { return v }
							return nil
						}()
					else { continue }
					continuation.yield(_sig0)
				}
				continuation.finish()
			}
			continuation.onTermination = { _ in task.cancel() }
		}
	}

	public func nameAcquired() async throws -> AsyncStream<String> {
		_ = try await connection.send(
			DBusRequest.createMethodCall(
				destination: "org.freedesktop.DBus",
				path: "/org/freedesktop/DBus",
				interface: "org.freedesktop.DBus",
				method: "AddMatch",
				body: [.string("type='signal',interface='org.freedesktop.DBus',member='NameAcquired'")],
			)
		)
		let rawStream = await connection.subscribeToSignal(
			interface: "org.freedesktop.DBus",
			member: "NameAcquired",
		)
		return AsyncStream<String> { continuation in
			let task = Task {
				for await message in rawStream {
					guard message.body.count >= 1 else { continue }
					guard
						let _sig0 = { () -> String? in
							if case .string(let v) = message.body[0] { return v }
							return nil
						}()
					else { continue }
					continuation.yield(_sig0)
				}
				continuation.finish()
			}
			continuation.onTermination = { _ in task.cancel() }
		}
	}

	public func activatableServicesChanged() async throws -> AsyncStream<Void> {
		_ = try await connection.send(
			DBusRequest.createMethodCall(
				destination: "org.freedesktop.DBus",
				path: "/org/freedesktop/DBus",
				interface: "org.freedesktop.DBus",
				method: "AddMatch",
				body: [
					.string(
						"type='signal',interface='org.freedesktop.DBus',member='ActivatableServicesChanged'"
					)
				],
			)
		)
		let rawStream = await connection.subscribeToSignal(
			interface: "org.freedesktop.DBus",
			member: "ActivatableServicesChanged",
		)
		return AsyncStream<Void> { continuation in
			let task = Task {
				for await _ in rawStream { continuation.yield(()) }
				continuation.finish()
			}
			continuation.onTermination = { _ in task.cancel() }
		}
	}

}

public protocol OrgFreedesktopDBusHandler: Sendable {
	func hello() async throws -> String
	func requestName(arg: String, arg: UInt32) async throws -> UInt32
	func releaseName(arg: String) async throws -> UInt32
	func startServiceByName(arg: String, arg: UInt32) async throws -> UInt32
	func updateActivationEnvironment(arg: [String: String]) async throws
	func nameHasOwner(arg: String) async throws -> Bool
	func listNames() async throws -> [String]
	func listActivatableNames() async throws -> [String]
	func addMatch(arg: String) async throws
	func removeMatch(arg: String) async throws
	func getNameOwner(arg: String) async throws -> String
	func listQueuedOwners(arg: String) async throws -> [String]
	func getConnectionUnixUser(arg: String) async throws -> UInt32
	func getConnectionUnixProcessID(arg: String) async throws -> UInt32
	func getAdtAuditSessionData(arg: String) async throws -> [UInt8]
	func getConnectionSELinuxSecurityContext(arg: String) async throws -> [UInt8]
	func getConnectionAppArmorSecurityContext(arg: String) async throws -> String
	func reloadConfig() async throws
	func getId() async throws -> String
	func getConnectionCredentials(arg: String) async throws -> [String: DBusVariant]
	var features: [String] { get async throws }
	var interfaces: [String] { get async throws }
}

extension OrgFreedesktopDBusHandler {
	public func makeInterface() -> DBusObjectServer.Interface {
		var iface = DBusObjectServer.Interface(name: "org.freedesktop.DBus")
		iface.methods = [
			.init(name: "Hello", inputArgs: [], outputArgs: [.init(name: "arg", type: "s")]) {
				[self] ctx in
				let result = try await self.hello()
				return [.string(result)]
			},
			.init(
				name: "RequestName",
				inputArgs: [.init(name: "arg", type: "s"), .init(name: "arg", type: "u")],
				outputArgs: [.init(name: "arg", type: "u")],
			) { [self] ctx in
				guard ctx.arguments.count >= 2 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				guard case .uint32(let arg) = ctx.arguments[1] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.requestName(arg: arg, arg: arg)
				return [.uint32(result)]
			},
			.init(
				name: "ReleaseName",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "u")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.releaseName(arg: arg)
				return [.uint32(result)]
			},
			.init(
				name: "StartServiceByName",
				inputArgs: [.init(name: "arg", type: "s"), .init(name: "arg", type: "u")],
				outputArgs: [.init(name: "arg", type: "u")],
			) { [self] ctx in
				guard ctx.arguments.count >= 2 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				guard case .uint32(let arg) = ctx.arguments[1] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.startServiceByName(arg: arg, arg: arg)
				return [.uint32(result)]
			},
			.init(
				name: "UpdateActivationEnvironment",
				inputArgs: [.init(name: "arg", type: "a{ss}")],
				outputArgs: [],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .dictionary(let _d_arg) = ctx.arguments[0] else {
					throw DBusCodegenError.typeMismatch
				}
				let arg = try Dictionary(
					uniqueKeysWithValues: _d_arg.map { k, v in
						guard case .string(let key) = k, case .string(let val) = v else {
							throw DBusCodegenError.typeMismatch
						}
						return (key, val)
					}
				)
				try await self.updateActivationEnvironment(arg: arg)
				return []
			},
			.init(
				name: "NameHasOwner",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "b")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.nameHasOwner(arg: arg)
				return [.boolean(result)]
			},
			.init(name: "ListNames", inputArgs: [], outputArgs: [.init(name: "arg", type: "as")]) {
				[self] ctx in
				let result = try await self.listNames()
				return [.array(result.map { .string($0) })]
			},
			.init(
				name: "ListActivatableNames",
				inputArgs: [],
				outputArgs: [.init(name: "arg", type: "as")],
			) { [self] ctx in
				let result = try await self.listActivatableNames()
				return [.array(result.map { .string($0) })]
			},
			.init(name: "AddMatch", inputArgs: [.init(name: "arg", type: "s")], outputArgs: []) {
				[self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				try await self.addMatch(arg: arg)
				return []
			},
			.init(name: "RemoveMatch", inputArgs: [.init(name: "arg", type: "s")], outputArgs: []) {
				[self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				try await self.removeMatch(arg: arg)
				return []
			},
			.init(
				name: "GetNameOwner",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "s")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.getNameOwner(arg: arg)
				return [.string(result)]
			},
			.init(
				name: "ListQueuedOwners",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "as")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.listQueuedOwners(arg: arg)
				return [.array(result.map { .string($0) })]
			},
			.init(
				name: "GetConnectionUnixUser",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "u")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.getConnectionUnixUser(arg: arg)
				return [.uint32(result)]
			},
			.init(
				name: "GetConnectionUnixProcessID",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "u")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.getConnectionUnixProcessID(arg: arg)
				return [.uint32(result)]
			},
			.init(
				name: "GetAdtAuditSessionData",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "ay")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.getAdtAuditSessionData(arg: arg)
				return [.array(result.map { .byte($0) })]
			},
			.init(
				name: "GetConnectionSELinuxSecurityContext",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "ay")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.getConnectionSELinuxSecurityContext(arg: arg)
				return [.array(result.map { .byte($0) })]
			},
			.init(
				name: "GetConnectionAppArmorSecurityContext",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "s")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.getConnectionAppArmorSecurityContext(arg: arg)
				return [.string(result)]
			},
			.init(name: "ReloadConfig", inputArgs: [], outputArgs: []) { [self] ctx in
				try await self.reloadConfig()
				return []
			},
			.init(name: "GetId", inputArgs: [], outputArgs: [.init(name: "arg", type: "s")]) {
				[self] ctx in
				let result = try await self.getId()
				return [.string(result)]
			},
			.init(
				name: "GetConnectionCredentials",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "a{sv}")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.getConnectionCredentials(arg: arg)
				return [
					.dictionary(
						Dictionary(uniqueKeysWithValues: result.map { (.string($0.key), .variant($0.value)) })
					)
				]
			},
		]
		iface.properties = [
			.init(
				name: "Features",
				signature: "as",
				access: .read,
				get: { [self] _ in .array(try await self.features.map { .string($0) }) },
			),
			.init(
				name: "Interfaces",
				signature: "as",
				access: .read,
				get: { [self] _ in .array(try await self.interfaces.map { .string($0) }) },
			),
		]
		return iface
	}
}

// MARK: - org.freedesktop.DBus.Properties

public protocol OrgFreedesktopDBusProperties: Sendable {
	func `get`(arg: String, arg: String) async throws -> DBusVariant
	func getAll(arg: String) async throws -> [String: DBusVariant]
	func `set`(arg: String, arg: String, arg: DBusVariant) async throws
	func propertiesChanged() async throws -> AsyncStream<
		(
			interfaceName: String, changedProperties: [String: DBusVariant],
			invalidatedProperties: [String]
		)
	>
}

public struct OrgFreedesktopDBusPropertiesProxy: OrgFreedesktopDBusProperties {
	private let connection: DBusClient.Connection
	private let destination: String
	private let path: String

	public init(connection: DBusClient.Connection, destination: String, path: String) {
		self.connection = connection
		self.destination = destination
		self.path = path
	}

	public func `get`(arg: String, arg: String) async throws -> DBusVariant {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus.Properties",
			method: "Get",
			body: [.string(arg), .string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .variant(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func getAll(arg: String) async throws -> [String: DBusVariant] {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus.Properties",
			method: "GetAll",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .dictionary(let _dict0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return try Dictionary(
			uniqueKeysWithValues: _dict0.map { k, v in
				guard case .string(let key) = k, case .variant(let val) = v else {
					throw DBusCodegenError.typeMismatch
				}
				return (key, val)
			}
		)
	}

	public func `set`(arg: String, arg: String, arg: DBusVariant) async throws {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus.Properties",
			method: "Set",
			body: [.string(arg), .string(arg), .variant(arg)],
		)
		_ = try await connection.send(request)
	}

	public func propertiesChanged() async throws -> AsyncStream<
		(
			interfaceName: String, changedProperties: [String: DBusVariant],
			invalidatedProperties: [String]
		)
	> {
		_ = try await connection.send(
			DBusRequest.createMethodCall(
				destination: "org.freedesktop.DBus",
				path: "/org/freedesktop/DBus",
				interface: "org.freedesktop.DBus",
				method: "AddMatch",
				body: [
					.string(
						"type='signal',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged'"
					)
				],
			)
		)
		let rawStream = await connection.subscribeToSignal(
			interface: "org.freedesktop.DBus.Properties",
			member: "PropertiesChanged",
		)
		return AsyncStream<
			(
				interfaceName: String, changedProperties: [String: DBusVariant],
				invalidatedProperties: [String]
			)
		> { continuation in
			let task = Task {
				for await message in rawStream {
					guard message.body.count >= 3 else { continue }
					guard
						let _sig0 = { () -> String? in
							if case .string(let v) = message.body[0] { return v }
							return nil
						}()
					else { continue }
					guard
						let _sig1 = { () -> [String: DBusVariant]? in
							guard case .dictionary(let _d) = message.body[1] else { return nil }
							var _r: [String: DBusVariant] = [:]
							for (k, v) in _d {
								guard case .string(let key) = k, case .variant(let val) = v else { return nil }
								_r[key] = val
							}
							return _r
						}()
					else { continue }
					guard
						let _sig2 = { () -> [String]? in
							guard case .array(let _a) = message.body[2] else { return nil }
							var _r: [String] = []
							for _e in _a {
								guard case .string(let s) = _e else { return nil }
								_r.append(s)
							}
							return _r
						}()
					else { continue }
					continuation.yield(
						(interfaceName: _sig0, changedProperties: _sig1, invalidatedProperties: _sig2)
					)
				}
				continuation.finish()
			}
			continuation.onTermination = { _ in task.cancel() }
		}
	}

}

public protocol OrgFreedesktopDBusPropertiesHandler: Sendable {
	func `get`(arg: String, arg: String) async throws -> DBusVariant
	func getAll(arg: String) async throws -> [String: DBusVariant]
	func `set`(arg: String, arg: String, arg: DBusVariant) async throws
}

extension OrgFreedesktopDBusPropertiesHandler {
	public func makeInterface() -> DBusObjectServer.Interface {
		var iface = DBusObjectServer.Interface(name: "org.freedesktop.DBus.Properties")
		iface.methods = [
			.init(
				name: "Get",
				inputArgs: [.init(name: "arg", type: "s"), .init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "v")],
			) { [self] ctx in
				guard ctx.arguments.count >= 2 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[1] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.`get`(arg: arg, arg: arg)
				return [.variant(result)]
			},
			.init(
				name: "GetAll",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "a{sv}")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.getAll(arg: arg)
				return [
					.dictionary(
						Dictionary(uniqueKeysWithValues: result.map { (.string($0.key), .variant($0.value)) })
					)
				]
			},
			.init(
				name: "Set",
				inputArgs: [
					.init(name: "arg", type: "s"), .init(name: "arg", type: "s"),
					.init(name: "arg", type: "v"),
				],
				outputArgs: [],
			) { [self] ctx in
				guard ctx.arguments.count >= 3 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[1] else { throw DBusCodegenError.typeMismatch }
				guard case .variant(let arg) = ctx.arguments[2] else { throw DBusCodegenError.typeMismatch }
				try await self.`set`(arg: arg, arg: arg, arg: arg)
				return []
			},
		]
		return iface
	}
}

// MARK: - org.freedesktop.DBus.Introspectable

public protocol OrgFreedesktopDBusIntrospectable: Sendable {
	func introspect() async throws -> String
}

public struct OrgFreedesktopDBusIntrospectableProxy: OrgFreedesktopDBusIntrospectable {
	private let connection: DBusClient.Connection
	private let destination: String
	private let path: String

	public init(connection: DBusClient.Connection, destination: String, path: String) {
		self.connection = connection
		self.destination = destination
		self.path = path
	}

	public func introspect() async throws -> String {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus.Introspectable",
			method: "Introspect",
			body: [],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .string(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}
}

public protocol OrgFreedesktopDBusIntrospectableHandler: Sendable {
	func introspect() async throws -> String
}

extension OrgFreedesktopDBusIntrospectableHandler {
	public func makeInterface() -> DBusObjectServer.Interface {
		var iface = DBusObjectServer.Interface(name: "org.freedesktop.DBus.Introspectable")
		iface.methods = [
			.init(name: "Introspect", inputArgs: [], outputArgs: [.init(name: "arg", type: "s")]) {
				[self] ctx in
				let result = try await self.introspect()
				return [.string(result)]
			}
		]
		return iface
	}
}

// MARK: - org.freedesktop.DBus.Monitoring

public protocol OrgFreedesktopDBusMonitoring: Sendable {
	func becomeMonitor(arg: [String], arg: UInt32) async throws
}

public struct OrgFreedesktopDBusMonitoringProxy: OrgFreedesktopDBusMonitoring {
	private let connection: DBusClient.Connection
	private let destination: String
	private let path: String

	public init(connection: DBusClient.Connection, destination: String, path: String) {
		self.connection = connection
		self.destination = destination
		self.path = path
	}

	public func becomeMonitor(arg: [String], arg: UInt32) async throws {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus.Monitoring",
			method: "BecomeMonitor",
			body: [.array(arg.map { .string($0) }), .uint32(arg)],
		)
		_ = try await connection.send(request)
	}
}

public protocol OrgFreedesktopDBusMonitoringHandler: Sendable {
	func becomeMonitor(arg: [String], arg: UInt32) async throws
}

extension OrgFreedesktopDBusMonitoringHandler {
	public func makeInterface() -> DBusObjectServer.Interface {
		var iface = DBusObjectServer.Interface(name: "org.freedesktop.DBus.Monitoring")
		iface.methods = [
			.init(
				name: "BecomeMonitor",
				inputArgs: [.init(name: "arg", type: "as"), .init(name: "arg", type: "u")],
				outputArgs: [],
			) { [self] ctx in
				guard ctx.arguments.count >= 2 else { throw DBusCodegenError.typeMismatch }
				guard case .array(let _arr_arg) = ctx.arguments[0] else {
					throw DBusCodegenError.typeMismatch
				}
				let arg = try _arr_arg.map { elem in
					guard case .string(let s) = elem else { throw DBusCodegenError.typeMismatch }
					return s
				}
				guard case .uint32(let arg) = ctx.arguments[1] else { throw DBusCodegenError.typeMismatch }
				try await self.becomeMonitor(arg: arg, arg: arg)
				return []
			}
		]
		return iface
	}
}

// MARK: - org.freedesktop.DBus.Debug.Stats

public protocol OrgFreedesktopDBusDebugStats: Sendable {
	func getStats() async throws -> [String: DBusVariant]
	func getConnectionStats(arg: String) async throws -> [String: DBusVariant]
	func getAllMatchRules() async throws -> DBusValue
}

public struct OrgFreedesktopDBusDebugStatsProxy: OrgFreedesktopDBusDebugStats {
	private let connection: DBusClient.Connection
	private let destination: String
	private let path: String

	public init(connection: DBusClient.Connection, destination: String, path: String) {
		self.connection = connection
		self.destination = destination
		self.path = path
	}

	public func getStats() async throws -> [String: DBusVariant] {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus.Debug.Stats",
			method: "GetStats",
			body: [],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .dictionary(let _dict0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return try Dictionary(
			uniqueKeysWithValues: _dict0.map { k, v in
				guard case .string(let key) = k, case .variant(let val) = v else {
					throw DBusCodegenError.typeMismatch
				}
				return (key, val)
			}
		)
	}

	public func getConnectionStats(arg: String) async throws -> [String: DBusVariant] {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus.Debug.Stats",
			method: "GetConnectionStats",
			body: [.string(arg)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .dictionary(let _dict0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return try Dictionary(
			uniqueKeysWithValues: _dict0.map { k, v in
				guard case .string(let key) = k, case .variant(let val) = v else {
					throw DBusCodegenError.typeMismatch
				}
				return (key, val)
			}
		)
	}

	public func getAllMatchRules() async throws -> DBusValue {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus.Debug.Stats",
			method: "GetAllMatchRules",
			body: [],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		return reply.body[0]
	}
}

public protocol OrgFreedesktopDBusDebugStatsHandler: Sendable {
	func getStats() async throws -> [String: DBusVariant]
	func getConnectionStats(arg: String) async throws -> [String: DBusVariant]
	func getAllMatchRules() async throws -> DBusValue
}

extension OrgFreedesktopDBusDebugStatsHandler {
	public func makeInterface() -> DBusObjectServer.Interface {
		var iface = DBusObjectServer.Interface(name: "org.freedesktop.DBus.Debug.Stats")
		iface.methods = [
			.init(name: "GetStats", inputArgs: [], outputArgs: [.init(name: "arg", type: "a{sv}")]) {
				[self] ctx in
				let result = try await self.getStats()
				return [
					.dictionary(
						Dictionary(uniqueKeysWithValues: result.map { (.string($0.key), .variant($0.value)) })
					)
				]
			},
			.init(
				name: "GetConnectionStats",
				inputArgs: [.init(name: "arg", type: "s")],
				outputArgs: [.init(name: "arg", type: "a{sv}")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let arg) = ctx.arguments[0] else { throw DBusCodegenError.typeMismatch }
				let result = try await self.getConnectionStats(arg: arg)
				return [
					.dictionary(
						Dictionary(uniqueKeysWithValues: result.map { (.string($0.key), .variant($0.value)) })
					)
				]
			},
			.init(
				name: "GetAllMatchRules",
				inputArgs: [],
				outputArgs: [.init(name: "arg", type: "a{sas}")],
			) { [self] ctx in
				let result = try await self.getAllMatchRules()
				return [result]
			},
		]
		return iface
	}
}

// MARK: - org.freedesktop.DBus.Peer

public protocol OrgFreedesktopDBusPeer: Sendable {
	func getMachineId() async throws -> String
	func ping() async throws
}

public struct OrgFreedesktopDBusPeerProxy: OrgFreedesktopDBusPeer {
	private let connection: DBusClient.Connection
	private let destination: String
	private let path: String

	public init(connection: DBusClient.Connection, destination: String, path: String) {
		self.connection = connection
		self.destination = destination
		self.path = path
	}

	public func getMachineId() async throws -> String {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus.Peer",
			method: "GetMachineId",
			body: [],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .string(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}

	public func ping() async throws {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "org.freedesktop.DBus.Peer",
			method: "Ping",
			body: [],
		)
		_ = try await connection.send(request)
	}
}

public protocol OrgFreedesktopDBusPeerHandler: Sendable {
	func getMachineId() async throws -> String
	func ping() async throws
}

extension OrgFreedesktopDBusPeerHandler {
	public func makeInterface() -> DBusObjectServer.Interface {
		var iface = DBusObjectServer.Interface(name: "org.freedesktop.DBus.Peer")
		iface.methods = [
			.init(name: "GetMachineId", inputArgs: [], outputArgs: [.init(name: "arg", type: "s")]) {
				[self] ctx in
				let result = try await self.getMachineId()
				return [.string(result)]
			},
			.init(name: "Ping", inputArgs: [], outputArgs: []) { [self] ctx in
				try await self.ping()
				return []
			},
		]
		return iface
	}
}
