// Generated by dbus-codegen. Do not edit.
import DBUS

private enum DBusCodegenError: Error { case typeMismatch }

// MARK: - com.balthild.Pliers

public protocol ComBalthildPliers: Sendable {
	func createLoginToken(pubkey: [UInt8]) async throws -> [UInt8]
}

public struct ComBalthildPliersProxy: ComBalthildPliers {
	private let connection: DBusClient.Connection
	private let destination: String
	private let path: String

	public init(connection: DBusClient.Connection, destination: String, path: String) {
		self.connection = connection
		self.destination = destination
		self.path = path
	}

	public func createLoginToken(pubkey: [UInt8]) async throws -> [UInt8] {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "com.balthild.Pliers",
			method: "CreateLoginToken",
			body: [.array(pubkey.map { .byte($0) })],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .array(let _arr0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return try _arr0.map { elem in
			guard case .byte(let b) = elem else { throw DBusCodegenError.typeMismatch }
			return b
		}
	}
}

public protocol ComBalthildPliersHandler: Sendable {
	func createLoginToken(pubkey: [UInt8]) async throws -> [UInt8]
}

extension ComBalthildPliersHandler {
	public func makeInterface() -> DBusObjectServer.Interface {
		var iface = DBusObjectServer.Interface(name: "com.balthild.Pliers")
		iface.methods = [
			.init(
				name: "CreateLoginToken",
				inputArgs: [.init(name: "pubkey", type: "ay")],
				outputArgs: [.init(name: "challenge", type: "ay")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .array(let _arr_pubkey) = ctx.arguments[0] else {
					throw DBusCodegenError.typeMismatch
				}
				let pubkey = try _arr_pubkey.map { elem in
					guard case .byte(let b) = elem else { throw DBusCodegenError.typeMismatch }
					return b
				}
				let result = try await self.createLoginToken(pubkey: pubkey)
				return [.array(result.map { .byte($0) })]
			}
		]
		return iface
	}
}
