// Generated by dbus-codegen. Do not edit.
import DBUS

private enum DBusCodegenError: Error { case typeMismatch }

// MARK: - com.balthild.Pliers

public protocol ComBalthildPliers: Sendable {
	func createLoginToken(pubkey: String) async throws -> String
}

public struct ComBalthildPliersProxy: ComBalthildPliers {
	private let connection: DBusClient.Connection
	private let destination: String
	private let path: String

	public init(connection: DBusClient.Connection, destination: String, path: String) {
		self.connection = connection
		self.destination = destination
		self.path = path
	}

	public func createLoginToken(pubkey: String) async throws -> String {
		let request = DBusRequest.createMethodCall(
			destination: destination,
			path: path,
			interface: "com.balthild.Pliers",
			method: "CreateLoginToken",
			body: [.string(pubkey)],
		)
		guard let reply = try await connection.send(request) else { throw DBusError.missingReply }
		guard reply.body.indices.contains(0) else { throw DBusCodegenError.typeMismatch }
		guard case .string(let _v0) = reply.body[0] else { throw DBusCodegenError.typeMismatch }
		return _v0
	}
}

public protocol ComBalthildPliersHandler: Sendable {
	func createLoginToken(pubkey: String) async throws -> String
}

extension ComBalthildPliersHandler {
	public func makeInterface() -> DBusObjectServer.Interface {
		var iface = DBusObjectServer.Interface(name: "com.balthild.Pliers")
		iface.methods = [
			.init(
				name: "CreateLoginToken",
				inputArgs: [.init(name: "pubkey", type: "s")],
				outputArgs: [.init(name: "challenge", type: "s")],
			) { [self] ctx in
				guard ctx.arguments.count >= 1 else { throw DBusCodegenError.typeMismatch }
				guard case .string(let pubkey) = ctx.arguments[0] else {
					throw DBusCodegenError.typeMismatch
				}
				let result = try await self.createLoginToken(pubkey: pubkey)
				return [.string(result)]
			}
		]
		return iface
	}
}
